version: 0.2

env:
  variables:
    ECR_REPO: "969317006731.dkr.ecr.us-east-1.amazonaws.com/repo-1"
    REGION: "us-east-1"
    CLUSTER_NAME: "cluster-1"
    DEPLOYMENT_NAME: "backend-deployment"
    CONTAINER_NAME: "backend"

phases:
  install:
    commands:
      - echo "Installing kubectl..."
      - curl -o kubectl https://amazon-eks.s3.amazonaws.com/1.29.0/2024-01-04/bin/linux/amd64/kubectl
      - chmod +x kubectl && mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REPO
      - echo "Updating kubeconfig..."
      - aws eks update-kubeconfig \
          --region $REGION \
          --name $CLUSTER_NAME \
          --role-arn arn:aws:iam::969317006731:role/codebuild-build-1-service-role
      - export KUBECONFIG=$HOME/.kube/config  # Ensure kubectl uses the right config

  build:
    commands:
      - echo "Building Docker image..."
      - cd backend
      - docker build -t backend .
      - docker tag backend:latest $ECR_REPO:latest

  post_build:
    commands:
      - echo "Pushing to ECR..."
      - docker push $ECR_REPO:latest
      - echo "Updating deployment image in EKS..."
      - kubectl get nodes        # Optional: verify connectivity
      - kubectl get pods -n kube-system  # Optional: verify cluster health
      - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$ECR_REPO:latest
      - echo "Backend deployment updated."

artifacts:
  files:
    - '**/*'
